#ddev-generated
web_environment:
  - MSSQL_EXTERNAL_PORT=1433
  - MSSQL_SA_PASSWORD=Password12!
  - MSSQL_PID=Developer
  - MSSQL_DB_NAME=drupal
  - MSSQL_HOST=localhost

hooks:
  post-start:
   - exec: echo export PATH="$PATH:/opt/mssql-tools/bin" >> ~/.bashrc
   - exec: source ~/.bashrc